### PR TITLE
Pass UID as an ARG to docker

### PR DESCRIPTION
**Pull request by lejan**
docker build arg variable UID added

### CODE REVIEW

**Review by GonzaCerv — APPROVED** [review]
Look good to me! (LGTM). Please remove the `Draft` in the title, and merge it

**Comment by GonzaCerv** [comment]
I also changed the title of this commit, so it is clear what is going on

**Comment by lejan** [comment]
I can't merge it:

"This branch has no conflicts with the base branch
Only those with write access to this repository can merge pull requests."

**Comment by GonzaCerv** [comment]
Ok, I will do it this time.

**Pull request merged**
